### ISSUE TITLE
Normal termination leads to log of exception: Debugger problem occurred

### ISSUE THREAD

**Issue by de-jcup** [de-jcup/eclipse-bash-editor#173]
Having a normal script executed - even when returning 0, it currently does always log an exception (and breakpoints are also sometimes no longer visible?!?!)
```
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.net.SocketInputStream.read(SocketInputStream.java:224)
	at de.jcup.basheditor.debug.BashNetworkConnector.stepBegin(BashNetworkConnector.java:110)
	at de.jcup.basheditor.debug.BashDebugger.process(BashDebugger.java:241)
	at de.jcup.basheditor.debug.element.BashDebugTarget$BashDebugTargetEventDispatchJob.run(BashDebugTarget.java:354)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

```

**Comment by de-jcup** [comment]
Did not happen any longer - maybe it was fixed by some side effects at developement changes of 2.3.0 - so closing
